/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        ivory: '#FDF8F3',
        charcoal: '#4A4340',
        forest: '#7BAF95',
        terra: '#C4A882',
        walnut: '#A09590',
        sand: '#F0E6D9',
        ocean: '#9DC4D4',
        deep: '#3A4F5C',
        sage: '#7BAF95',
        earthBrown: '#C4A882',
        mutedBrown: '#A09590',
        beige: '#F0E6D9',
        // Stitch admin design system
        primary: '#3e674b',
        'primary-container': '#7ba787',
        'primary-fixed': '#bfeeca',
        'on-primary': '#ffffff',
        'on-primary-container': '#113c24',
        secondary: '#9a442d',
        'secondary-container': '#fc9174',
        'on-secondary-container': '#742814',
        tertiary: '#45645e',
        'tertiary-container': '#83a49c',
        surface: '#fcf9f4',
        'surface-dim': '#dcdad5',
        'surface-variant': '#e5e2dd',
        'surface-container': '#f0ede9',
        'surface-container-low': '#f6f3ee',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e5e2dd',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#414942',
        'on-background': '#1c1c19',
        outline: '#717972',
        'outline-variant': '#c1c9c0',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'brand-bg': '#FAF7F2',
        'brand-primary': '#E07A5F',
        'brand-secondary': '#7BA787',
        'brand-accent': '#D4A843',
        'brand-text': '#2C2C2C',
        'brand-text-light': '#4A4A4A',
        'brand-muted': '#8A8778',
        'brand-coral-light': '#FFF0EC',
        'brand-coral-dark': '#C45B4A',
      },
      fontFamily: {
        serif: ['"Cormorant Garamond"', 'serif'],
        headline: ['"EB Garamond"', 'serif'],
        body: ['Outfit', 'sans-serif'],
        sans: ['Outfit', 'sans-serif'],
        label: ['"DM Sans"', 'sans-serif'],
      },
      spacing: {
        '120': '30rem',
        '160': '40rem',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
